- name: Install bash
  ansible.builtin.package:
    name:
      - bash
    state: present

- name: Configure bash for Dmitry Ilvokhin
  ansible.builtin.include_role:
    name: bashrc
  tags:
    - dotfiles
