- name: Install mutt
  ansible.builtin.package:
    name:
      - mutt
    state: present

- name: Configure mutt for Dmitry Ilvokhin
  ansible.builtin.include_role:
    name: muttrc
  tags:
    - dotfiles
