- name: Copy necessary dotfiles
  hosts: localhost
  vars:
    dotfiles_user: '{{ lookup("env", "USER") }}'
    # Ideally group should be something like `id -gn {{ dotfiles_user }}`
    # instead.
    dotfiles_group: "{{ lookup('ansible.builtin.vars', 'user') \
        if ansible_os_family != \"Darwin\" else 'staff' }}"
    dotfiles_homedir: '{{ lookup("env", "HOME") }}'
  roles:
    - { role: dotfiles }
