digitalocean:
  hosts:
    gate.ilvokhin.com:
    sun.ilvokhin.com:
    mail.ilvokhin.com:

web:
  hosts:
    sun.ilvokhin.com:

mail:
  hosts:
    mail.ilvokhin.com:

vpn:
  hosts:
    gate.ilvokhin.com:

shell:
  hosts:
    gate.ilvokhin.com:
