- name: Update DigitalOcean machines
  hosts: digitalocean
  vars:
    digitalocean_api_url: https://api.digitalocean.com/v2
  vars_files:
    - misc/secrets/digitalocean.yml
  roles:
    - { role: shutdown }
    - { role: snapshot }
    - { role: poweron }
    - { role: sysupgrade }
    - { role: reboot }
