- name: Setup machines to serve web traffic
  hosts: web
  roles:
    # Websites
    - { role: home }
    - { role: ip }
    - { role: blog }
    - { role: packages }
    # Git
    - { role: gitserver }
    - { role: cgit }
