- name: Install irssi package
  ansible.builtin.package:
    name:
      - irssi
    state: present

- name: Configure irssi for Dmitry Ilvokhin
  ansible.builtin.include_role:
    name: irssiconf
  tags:
    - dotfiles
