- name: Restart wgvpn
  ansible.builtin.service:
    name: wg-quick@wgvpn0
    state: restarted

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
