- name: Restart wgvpn
  ansible.builtin.service:
    name: wg-quick@wg1
    state: restarted

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restart
