# This role is a little bit different from others, because it is supposed to
# run mostly from localhost to make and copy dotfiles that might be useful on
# this particular machine. There is maybe not enough permissions to install
# software, so we are taking unusual approach here: check if software is
# installed and then bring relevant dotfiles for it.

- name: Configure bash if installed
  tags: bash
  block:
    - name: Check if bash is installed
      ansible.builtin.command: bash --version
      changed_when: false
      failed_when: false
      register: has_bash

    - ansible.builtin.include_role:
        name: bashrc
      vars:
        bashrc_user: '{{ user }}'
        bashrc_group: '{{ group }}'
        bashrc_homedir: '{{ homedir }}'
      when: has_bash.rc == 0

- name: Configure vim if installed
  tags: vim
  block:
    - name: Check if vim is installed
      ansible.builtin.command: vim --version
      changed_when: false
      failed_when: false
      register: has_vim

    - ansible.builtin.include_role:
        name: vimrc
      vars:
        vimrc_user: '{{ user }}'
        vimrc_group: '{{ group }}'
        vimrc_homedir: '{{ homedir }}'
      when: has_vim.rc == 0

- name: Configure screen if installed
  tags: screen
  block:
    - name: Check if screen is installed
      ansible.builtin.command: screen --version
      changed_when: false
      failed_when: false
      register: has_screen

    - ansible.builtin.include_role:
        name: screenrc
      vars:
        screenrc_user: '{{ user }}'
        screenrc_group: '{{ group }}'
        screenrc_homedir: '{{ homedir }}'
        screenrc_jumphost: '{{ jumphost }}'
      when: has_screen.rc == 0

- name: Configure ssh if installed
  tags: ssh
  block:
    - name: Check if ssh is installed
      ansible.builtin.command: ssh -V
      changed_when: false
      failed_when: false
      register: has_ssh

    - ansible.builtin.include_role:
        name: sshconfig
      vars:
        sshconfig_user: '{{ user }}'
        sshconfig_group: '{{ group }}'
        sshconfig_homedir: '{{ homedir }}'
        sshconfig_jumphost: '{{ jumphost }}'
      when: has_ssh.rc == 0

- name: Configure git if installed
  tags: git
  block:
    - name: Check if git is installed
      ansible.builtin.command: git --version
      changed_when: false
      failed_when: false
      register: has_git

    - ansible.builtin.include_role:
        name: gitconfig
      vars:
        gitconfig_user: '{{ user }}'
        gitconfig_group: '{{ group }}'
        gitconfig_homedir: '{{ homedir }}'
      when: has_git.rc == 0

- name: Configure gdb if installed
  tags: gdb
  block:
    - name: Check if gdb is installed
      ansible.builtin.command: gdb --version
      changed_when: false
      failed_when: false
      register: has_gdb

    - name: Copy gdbinit to home directory
      ansible.builtin.copy:
        src: misc/dotfiles/gdbinit
        dest: '{{ homedir }}/.gdbinit'
      when: has_gdb.rc == 0

- name: Configure mutt if installed
  tags: mutt
  block:
    - name: Check if mutt is installed
      ansible.builtin.command: mutt -v
      changed_when: false
      failed_when: false
      register: has_mutt

    - name: Copy muttrc to home directory
      ansible.builtin.copy:
        src: misc/dotfiles/muttrc
        dest: '{{ homedir }}/.muttrc'
      when: has_mutt.rc == 0

- name: Configure go if installed
  tags: go
  block:
    - name: Check if go is installed
      ansible.builtin.command: go version
      changed_when: false
      failed_when: false
      register: has_go

    - name: Set go config directory for macOS
      set_fact:
        go_conf_dir: '{{ homedir }}/Library/Application Support/go'
      when: has_go.rc == 0 and ansible_os_family == "Darwin"

    - name: Set go config directory for Linux
      set_fact:
        go_conf_dir: '{{ homedir }}/.config/go'
      when: has_go.rc == 0 and ansible_os_family != "Darwin"

    - name: Create go config directory
      ansible.builtin.file:
        path: '{{ go_conf_dir }}'
        state: directory
        owner: '{{ user }}'

    - name: Configure go enviroment
      ansible.builtin.template:
        src: misc/dotfiles/goenv.j2
        dest: '{{ go_conf_dir }}/env'
      when: has_go.rc == 0

- name: Copy templates files if necessary
  tags: templates
  block:
    - name: Check if C++ compiler is installed
      ansible.builtin.command: c++ --version
      changed_when: false
      failed_when: false
      register: has_cpp

    - name: Check if Python is installed
      ansible.builtin.command: python --version
      changed_when: false
      failed_when: false
      register: has_python

    - name: Setup templates directory
      ansible.builtin.file:
        path: '{{ homedir }}/.templates'
        state: directory
        owner: '{{ user }}'
      when: has_cpp.rc == 0 or has_python.rc == 0

    - name: Copy template.cpp to home directory
      ansible.builtin.copy:
        src: misc/dotfiles/templates/template.cpp
        dest: '{{ homedir }}/.templates/template.cpp'
      when: has_cpp.rc == 0

    - name: Copy benchmark.cpp to home directory
      ansible.builtin.copy:
        src: misc/dotfiles/templates/benchmark.cpp
        dest: '{{ homedir }}/.templates/benchmark.cpp'
      when: has_cpp.rc == 0

    - name: Copy template.py to home directory
      ansible.builtin.copy:
        src: misc/dotfiles/templates/template.py
        dest: '{{ homedir }}/.templates/template.py'
      when: has_python.rc == 0
