- name: Configure IPv4 packet forwarding
  ansible.builtin.copy:
    src: files/99-net-ipv4-forward.conf
    dest: /etc/sysctl.d/99-net-ipv4-forward.conf
    owner: root
    group: root
    mode: u+rw,g+r,o+r
  notify:
    - Restart systemd-sysctl
