- name: Setup SSH directory for Dmitry Ilvokhin
  ansible.builtin.file:
    path: /home/d/.ssh
    state: directory
    owner: d
    group: d
    mode: u+rw,g-wx,o-rwx
  tags:
    - dotfiles

- name: Update authorized_keys for Dmitry Ilvokhin
  ansible.posix.authorized_key:
    user: d
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - misc/pubkeys/*.pub
  tags:
    - dotfiles

- name: Configure ssh for Dmitry Ilvokhin
  ansible.builtin.include_role:
    name: sshconfig
  tags:
    - dotfiles
