- name: Create /srv/http/ilvokhin.com directory
  ansible.builtin.file:
    path: /srv/http/ilvokhin.com
    state: directory
    owner: http
    group: http
    mode: u+rw,g+rw,o+r

- name: Configure nginx for ilvokhin.com
  ansible.builtin.copy:
    src: files/ilvokhin.com
    dest: /etc/nginx/sites-available
    owner: root
    group: root
    mode: u+rw,g+r,o+r
  notify:
    - Reload nginx

- name: Enable ilvokhin.com site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/ilvokhin.com
    dest: /etc/nginx/sites-enabled/ilvokhin.com
    owner: root
    group: root
    mode: u+rw,g+r,o+r
    state: link
  notify:
    - Reload nginx
