- name: Install certbot package
  ansible.builtin.package:
    name:
      - '{{ item }}'
    state: present
  loop:
    - certbot

- name: Configure certbot systemd service
  ansible.builtin.copy:
    src: files/certbot.service
    dest: /usr/lib/systemd/system
    owner: root
    group: root
    mode: u+rw,g+r,o+r

- name: Configure certbot systemd timer
  ansible.builtin.copy:
    src: files/certbot.timer
    dest: /usr/lib/systemd/system
    owner: root
    group: root
    mode: u+rw,g+r,o+r

- name: Enable certbot systemd timer
  ansible.builtin.service:
    name: certbot.timer
    enabled: yes
    state: started
