- name: Remove default users
  ansible.builtin.user:
    name: '{{ item }}'
    state: absent
  loop:
    - arch

- name: Create user for Dmitry Ilvokhin
  ansible.builtin.user:
    name: d
    home: /home/d
    groups:
      - wheel
      # Group http required to deploy websites with rsync under personal
      # username.
      - http
