- name: Remove default users
  ansible.builtin.user:
    name: '{{ item }}'
    state: absent
  loop:
    - arch

- name: Create user for Dmitry Ilvokhin
  ansible.builtin.user:
    name: d
    home: /home/d
    groups:
      - wheel
      - http

- name: Setup SSH directory for Dmitry Ilvokhin
  ansible.builtin.file:
    path: /home/d/.ssh
    state: directory
    owner: d
    group: d
    mode: u+rw,g-wx,o-rwx

- name: Update authorized_keys for Dmitry Ilvokhin
  ansible.builtin.copy:
    src: files/id_rsa.pub
    dest: /home/d/.ssh/authorized_keys
    owner: d
    group: d
    mode: u+rw,g-rwx,o-rwx
