" Enable ruler (will display line number and column number by default).
set ruler

" Enable syntax highlight.
syntax on

" Expand tabs to spaces.
set expandtab

" In Makefiles, don't expand tabs to spaces, since we need the actual tabs.
autocmd FileType make setlocal noexpandtab

" Use four-space indentation by default.
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Use two-space indentation for yaml files.
autocmd FileType yaml setlocal tabstop=2
autocmd FileType yaml setlocal softtabstop=2
autocmd FileType yaml setlocal shiftwidth=2

" Limit text width.
set textwidth=79

" Limit width to 72 columns for git commit messages.
autocmd FileType gitcommit setlocal textwidth=72

" Disable incremental search.
set noincsearch

" Disable highlighting of the search results.
set nohlsearch

" Disable incremental search.
set noincsearch
