" Enable ruler (will display line number and column number by default).
set ruler

" Enable syntax highlight.
syntax on

" Expand tabs to spaces.
set expandtab

" Use four-space indentation by default.
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Limit text width.
set textwidth=79

" Do not expand tabs and use eight space indentation for C files.
autocmd FileType c setlocal noexpandtab
autocmd FileType c setlocal tabstop=8
autocmd FileType c setlocal softtabstop=8
autocmd FileType c setlocal shiftwidth=8

" Same for Go files.
autocmd FileType go setlocal noexpandtab
autocmd FileType go setlocal tabstop=8
autocmd FileType go setlocal softtabstop=8
autocmd FileType go setlocal shiftwidth=8

" In Makefiles, don't expand tabs to spaces, since we need the actual tabs.
autocmd FileType make setlocal noexpandtab

" Use two-space indentation for yaml files.
autocmd FileType yaml setlocal tabstop=2
autocmd FileType yaml setlocal softtabstop=2
autocmd FileType yaml setlocal shiftwidth=2

" Limit width to 72 columns for git commit messages.
autocmd FileType gitcommit setlocal textwidth=72

" And mail messages as well.
autocmd FileType mail setlocal textwidth=72

" Disable incremental search.
set noincsearch

" Disable highlighting of the search results.
set nohlsearch

" Disable incremental search.
set noincsearch
