- name: Configure WireGuard for wgtor
  ansible.builtin.template:
    src: templates/wgtor0.conf.j2
    dest: /etc/wireguard/wgtor0.conf
    owner: root
    group: root
    mode: u+rw,g-rw,o-rw
  notify: Restart wgtor

- name: Enable WireGuard service for wgtor
  ansible.builtin.service:
    name: wg-quick@wgtor0
    enabled: yes
    state: started
