- name: Install git
  ansible.builtin.package:
    name:
      - git
    state: present

- name: Create git user
  ansible.builtin.user:
    name: git
    shell: /usr/bin/git-shell
    home: /srv/git

- name: Setup SSH directory for Git
  ansible.builtin.file:
    path: /srv/git/.ssh
    state: directory
    owner: git
    group: git
    mode: u+rw,g-w,o-rwx

- name: Update authorized_keys for Git
  ansible.posix.authorized_key:
    user: git
    state: present
    # Workaround to make it work `with_fileglob`.
    # https://github.com/ansible/ansible/issues/48819#issuecomment-623851751
    key: "{{ lookup('file', item) }}"
    key_options: no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty
  with_fileglob:
    - misc/pubkeys/*.pub

# Private key is required to mirror repositories to GitHub.
- name: Copy private key for Git
  ansible.builtin.copy:
    src: files/id_rsa
    dest: /srv/git/.ssh/id_rsa
    owner: git
    group: git
    mode: u+rw,g-rwx,o-rwx

# We need to know github.com ssh keys before pushing there, otherwise
# post-receive will fail asking to verify authenticity of host.
# Run `ssh-keyscan github.com` to re-generate keys if required.
- name: Copy known_hosts for Git
  ansible.builtin.copy:
    src: files/known_hosts
    dest: /srv/git/.ssh/known_hosts
    owner: git
    group: git
    mode: u+rw,g-rwx,o-rwx

- name: Setup git-shell-commands directory
  ansible.builtin.file:
    path: /srv/git/git-shell-commands
    state: directory
    owner: git
    group: git
    mode: u+rwx,g+r,o+rx

- name: Copy no-interactive-login command
  ansible.builtin.copy:
    src: files/no-interactive-login
    dest: /srv/git/git-shell-commands
    owner: git
    group: git
    mode: u+rwx,g+r,o+r

- name: Configure git system-wide
  ansible.builtin.copy:
    src: files/gitconfig
    dest: /etc/gitconfig
    owner: git
    group: git
    mode: u+rwx,g+r,o+r

- name: Configure git-daemon systemd service
  ansible.builtin.copy:
    src: files/git-daemon.service
    dest: /usr/lib/systemd/system/git-daemon@.service
    owner: root
    group: root
    mode: u+rw,g+r,o+r

- name: Enable git-daemon
  ansible.builtin.systemd_service:
    name: git-daemon.socket
    enabled: true
    state: started
    daemon_reload: true

- name: Copy git.conf to handle git HTTP requests
  ansible.builtin.copy:
    src: files/git.conf
    dest: /etc/nginx/includes/git.conf
    owner: root
    group: root
    mode: u+rw,g+rw,o+r
  notify:
    - Reload nginx

- name: Configure nginx for git.ilvokhin.com
  ansible.builtin.copy:
    src: files/git.ilvokhin.com
    dest: /etc/nginx/sites-available
    owner: root
    group: root
    mode: u+rw,g+r,o+r
  notify:
    - Reload nginx

- name: Enable git.ilvokhin.com site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/git.ilvokhin.com
    dest: /etc/nginx/sites-enabled/git.ilvokhin.com
    owner: root
    group: root
    mode: u+rw,g+r,o+r
    state: link
  notify:
    - Reload nginx

- name: Copy managing scripts
  ansible.builtin.copy:
    src: files/init-git-repo.sh
    dest: /srv/git/init-git-repo.sh
    owner: git
    group: git
    mode: u+rwx,g-rwx,o-rwx
