- name: Install logrotate
  ansible.builtin.package:
    name:
      - logrotate
    state: present

- name: Enable logrotate timer
  ansible.builtin.service:
    name: logrotate.timer
    enabled: yes
    state: started
