- name: Install nginx
  ansible.builtin.package:
    name:
      - nginx
    state: present

- name: Enable nginx systemd unit 
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started

- name: Setup sites directories to serve by nginx
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: u+rw,g+r,o+r
  loop:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Configure nginx
  ansible.builtin.copy:
    src: roles/web/files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: u+rw,g+,o+r
  notify:
    - Reload nginx

# TODO: logrotate
