- name: Install screen
  ansible.builtin.package:
    name:
      - screen
    state: present

- name: Configure screen for Dmitry Ilvokhin
  ansible.builtin.include_role:
    name: screenrc
  tags:
    - dotfiles
