- name: Install vim
  ansible.builtin.package:
    name:
      - vim
    state: present

- name: Configure vim for Dmitry Ilvokhin
  ansible.builtin.include_role:
    name: vimrc
  tags:
    - dotfiles
