- name: Install fcgiwrap
  ansible.builtin.package:
    name:
      - fcgiwrap
    state: present

- name: Enable fcgiwrap.socket
  ansible.builtin.service:
    name: fcgiwrap.socket
    enabled: true
    state: started
