- name: Install gdb
  ansible.builtin.package:
    name:
      - gdb
    state: present

- name: Configure gdb for Dmitry Ilvokhin
  ansible.builtin.include_role:
    name: gdbinit
  tags:
    - dotfiles
