- ansible.builtin.include_role:
    name: nginx

- name: Configure nginx for ip.ilvokhin.com
  ansible.builtin.copy:
    src: files/ip.ilvokhin.com
    dest: /etc/nginx/sites-available
    owner: root
    group: root
    mode: u+rw,g+r,o+r
